// Copyright (c) 2020-2022, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/OmniAttr.h>
#include <omni/core/Interface.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <utility>
#include <type_traits>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
static_assert(std::is_standard_layout<omni::core::UInt2>::value,
              "omni::core::UInt2 must be standard layout to be used in ONI ABI");
static_assert(std::is_standard_layout<omni::core::Int2>::value,
              "omni::core::Int2 must be standard layout to be used in ONI ABI");
static_assert(std::is_standard_layout<omni::core::Float2>::value,
              "omni::core::Float2 must be standard layout to be used in ONI ABI");
