// Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// NOTE: This file is generated by 'make_version.lua' and should not be modified directly.
//
//! @file
//! @brief Defines a macro containing the SDK version this header was built with.
#pragma once

//! Version string for this SDK build.  This string is also returned by carbGetSdkVersion().
//! This value can be passed to @ref CARB_IS_SAME_SDK_VERSION() to verify that the loaded
//! version of the Carbonite framework library matches the headers that are in use.
#define CARB_SDK_VERSION "137.0+release137.tc7044.d7c525f0"
